### ISSUE TITLE
Does it support Turkey?

### ISSUE THREAD

**Issue by fguby** [AleNegrini/PyCristoforo#29]
I need to generate some coordinates in Turkey, but I am not sure if PyCristoforo support this country.

**Comment by AleNegrini** [comment]
Hello @fguby, 
sorry for the huge delay. Yes, Turkey is supported. 

If you want to test it: 
>>> import pycristoforo as pyc
>>> country = pyc.get_shape("Turkey")
>>> points = pyc.geoloc_generation(country, 100, "Turkey")
>>> points (in order to check the random generated points)
